version: '3.8'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "7072:7072"
    container_name: Api
    environment:
      - DOTNET_APPSETTINGS_FILE=/app/appsettings.json
      - ASPNETCORE_ENVIRONMENT=Docker
    env_file: 
      - ./Api/.env 
    volumes:
      - ./Api/appsettings.Docker.json:/app/appsettings.json:ro
      - ./Api/Persistance:/app/Persistance
    depends_on:
      - redis
      - elasticsearch
      - kibana
      - azurite
    networks:
    - elastic

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server"]
    networks:
    - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
    - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
    - elastic
    ports:
      - "5601:5601"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000" # Blob Storage
      - "10001:10001" # Queue Storage
      - "10002:10002" # Table Storage
    volumes:
      - azurite-data:/data
    command: >
      azurite
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --tableHost 0.0.0.0
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
  azurite-data:

